runtime: python37

entrypoint: gunicorn main:app --preload -b :$PORT

handlers:
- url: /static
  static_dir: staticfiles/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "holosongranker.settings"