# Generated by Django 4.0.3 on 2022-04-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer_Song',
        ),
    ]
