# Generated by Django 4.0.3 on 2022-04-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'song', 'verbose_name_plural': 'songs'},
        ),
    ]
