# Generated by Django 4.0.3 on 2022-04-10 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_delete_singer_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name', '-publish_at'], 'verbose_name': 'song', 'verbose_name_plural': 'songs'},
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='資料取得日期')),
                ('view', models.IntegerField(blank=True, verbose_name='觀看數')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_records', to='datas.song', verbose_name='歌曲')),
            ],
        ),
    ]
