# Generated by Django 4.0.3 on 2022-04-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_alter_song_options_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='view',
        ),
        migrations.AddField(
            model_name='record',
            name='total_view',
            field=models.IntegerField(blank=True, default=0, verbose_name='總觀看數'),
        ),
        migrations.AddField(
            model_name='record',
            name='weekly_view',
            field=models.IntegerField(blank=True, default=0, verbose_name='周觀看數成長'),
        ),
    ]
