# Generated by Django 4.0.3 on 2022-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_remove_record_view_record_total_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='unit',
            field=models.CharField(choices=[('Gen-0', 'Gen 0'), ('1STGEN', 'Gen 1'), ('Gen-2', 'Gen 2'), ('Gamers', 'Gamers'), ('Gen-3', 'Gen 3'), ('Gen-4', 'Gen 4'), ('Gen-5', 'Gen 5'), ('holoX', 'Holox'), ('Indonisia', 'In'), ('English', 'En'), ('Myth', 'Myth'), ('Project-hope', 'Hope'), ('Council', 'Council'), ('Group', 'Group')], max_length=255, verbose_name='所屬身分'),
        ),
        migrations.AlterField(
            model_name='group',
            name='vtuber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtuber_groups', to='datas.vtuber', verbose_name='Vtuber姓名'),
        ),
    ]
