# Generated by Django 4.0.3 on 2022-05-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_vtuberrecord'),
    ]

    operations = [
        migrations.RenameField('VtuberRecord', 'total_view_weekly_growth ', 'weekly_view'),
        migrations.RenameField('VtuberRecord', 'average_view_weekly_growth', 'average_weekly_view'),
    ]
