# Generated by Django 4.0.3 on 2022-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_remove_record_view_record_total_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='unit',
            field=models.CharField(choices=[('Gen-0', 'Gen 0'), ('1STGEN', 'Gen 1'), ('Gen-2', 'Gen 2'), ('Gamers', 'Gamers'), ('Gen-3', 'Gen 3'), ('Gen-4', 'Gen 4'), ('Gen-5', 'Gen 5'), ('holoX', 'Holox'), ('Indonisia', 'In'), ('English', 'En'), ('Myth', 'Myth'), ('Project-hope', 'Hope'), ('Council', 'Council'), ('Group', 'Group')], max_length=255, verbose_name='所屬身分'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='影片ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='影片連結'),
        ),
    ]
