# Generated by Django 4.0.3 on 2022-04-18 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_alter_group_unit_alter_song_youtube_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtuberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_view', models.IntegerField(blank=True, default=0, verbose_name='總觀看數')),
                ('total_view_weekly_growth', models.IntegerField(blank=True, default=0, verbose_name='周總觀看數成長')),
                ('average_view', models.IntegerField(blank=True, default=0, verbose_name='平均觀看數')),
                ('average_view_weekly_growth', models.IntegerField(blank=True, default=0, verbose_name='平均觀看數週成長')),
                ('song_count', models.IntegerField(blank=True, default=0, verbose_name='歌曲數量')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='資料取得日期')),
                ('vtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtuber_record', to='datas.vtuber', verbose_name='Vtuber姓名')),
            ],
        ),
    ]
