# Generated by Django 4.0.3 on 2022-03-26 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Vtuber姓名')),
                ('youtube_id', models.CharField(max_length=50, unique=True, verbose_name='Youtube ID')),
                ('youtube_url', models.CharField(blank=True, max_length=255, verbose_name='Youtube連結')),
                ('thumbnail_url', models.URLField(blank=True, max_length=255, verbose_name='頻道縮圖連結')),
            ],
            options={
                'db_table': 'vtuber',
                'ordering': ['name', 'youtube_id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='歌曲曲名')),
                ('youtube_id', models.URLField(max_length=255, unique=True, verbose_name='影片連結')),
                ('thumbnail_url', models.URLField(blank=True, max_length=255, verbose_name='縮圖連結')),
                ('youtube_url', models.URLField(blank=True, max_length=255, verbose_name='縮圖連結')),
                ('publish_at', models.DateField(default=django.utils.timezone.now, verbose_name='發行日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_songs', to='songs.vtuber', verbose_name='影片持有人')),
                ('singer', models.ManyToManyField(related_name='sing_songs', to='songs.vtuber', verbose_name='歌手')),
            ],
            options={
                'db_table': 'song',
                'ordering': ['-publish_at', 'name', 'owner'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Gen-0', 'Gen 0'), ('1STGEN', 'Gen 1'), ('Gen-2', 'Gen 2'), ('Gamers', 'Gamers'), ('Gen-3', 'Gen 3'), ('Gen-4', 'Gen 4'), ('Gen-5', 'Gen 5'), ('holoX', 'Holox'), ('Innk-music', 'Innk'), ('Indonisia', 'In'), ('English', 'En'), ('Myth', 'Myth'), ('Project-hope', 'Hope'), ('Council', 'Council'), ('Og', 'Og')], max_length=255, verbose_name='所屬身分')),
                ('vtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='songs.vtuber', verbose_name='Vtuber姓名')),
            ],
            options={
                'db_table': 'hololive',
                'ordering': ['unit', 'vtuber'],
            },
        ),
    ]
